apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx-skaffold
  name: nginx-skaffold
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-skaffold
  template:
    metadata:
      labels:
        app: nginx-skaffold
    spec:
      containers:
        - image: docker-registry.default.svc:5000/myproject/demo
          name: nginx-skaffold
          ports:
            - containerPort: 8080
              name: 8080-tcp
              protocol: TCP
          imagePullPolicy: Always
